name: assignment8
channels:
  - defaults
  - conda-forge
dependencies:
  - nbconvert=5.6.1
  - numpy=1.18.1
  - scipy=1.4.1
  - scikit-image=0.16.2
  - opencv=4.2.0
  - ipython=7.12.0
  - python=3.8.1
  - matplotlib=3.1.3
  - opencv=4.2.0
